import { useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const APP_URL = "https://app.havvo.co.uk";
type Page = "home" | "managers" | "trades" | "how" | "pricing" | "safety" | "contact";

const sections = {
  managers: ["One clear queue for every property", "Approve quotes, visits and completed work", "A complete record for every decision"],
  trades: ["Win well-scoped local work", "Keep photos, messages and sign-off in one job", "Get paid through your own connected Stripe account"],
};

function App() {
  const [page, setPage] = useState<Page>("home");
  const [menu, setMenu] = useState(false);
  const [sent, setSent] = useState(false);
  const go = (next: Page) => { setPage(next); setMenu(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const nav: Array<[Page, string]> = [["how", "How it works"], ["managers", "For property teams"], ["trades", "For trades"], ["pricing", "Pricing"], ["safety", "Safety"]];
  const hero = page === "home";
  return <><header className="nav"><button className="brand" onClick={() => go("home")}>havvo<span>.</span></button><nav className={menu ? "open" : ""}>{nav.map(([id,label]) => <button key={id} onClick={() => go(id)} className={page === id ? "active" : ""}>{label}</button>)}</nav><div className="nav-actions"><button className="login" onClick={() => location.assign(APP_URL)}>Sign in</button><button className="primary compact" onClick={() => go("contact")}>Join Havvo</button></div><button className="menu" aria-label="Open menu" onClick={() => setMenu(!menu)}>☰</button></header>
  {hero ? <Home go={go} /> : <PageView page={page} go={go} sent={sent} setSent={setSent} />}
  <footer><div><button className="brand" onClick={() => go("home")}>havvo<span>.</span></button><p>Property work, kept moving.</p></div><div className="footer-links">{nav.map(([id,label]) => <button key={id} onClick={() => go(id)}>{label}</button>)}<button onClick={() => go("contact")}>Contact</button><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a><a href="/cookies.html">Cookies</a><a href="/legal-identity.html">Legal identity</a></div><small>© {new Date().getFullYear()} Zweet Limited.</small></footer></>;
}

function Home({ go }: { go: (page: Page) => void }) { return <main><section className="hero"><div className="hero-copy"><p className="kicker">UK PROPERTY OPERATIONS</p><h1>Every property repair, <em>kept moving.</em></h1><p className="lede">Havvo brings tenants, property teams and trusted trades into one calm, accountable workspace — from first report to final sign-off.</p><div className="cta"><button className="primary" onClick={() => go("contact")}>Join the early access list <span>→</span></button><button className="text-button" onClick={() => go("how")}>See how it works <span>↓</span></button></div><p className="fine">Built for residential property teams and independent trades across the UK.</p></div><div className="hero-visual"><div className="glow" /><div className="device"><div className="device-top"><b>18 King Street</b><span>•••</span></div><div className="job-title"><i>⌂</i><div><small>ACTIVE REPAIR</small><b>Kitchen sink leak</b><span>Today · 15:30–16:00</span></div></div><div className="timeline"><p><i className="done" />Issue reported <span>09:12</span></p><p><i className="done" />Jordan confirmed visit <span>09:24</span></p><p><i className="live" />Trade is on the way <span>Now</span></p></div><div className="message"><b>Jordan · Plumber</b><p>I’ll ring the bell when I arrive.</p><small>14:58 ✓✓</small></div><div className="approval"><span>✓</span><div><b>Everything in one place</b><small>Chat, photos, approval and payment</small></div></div></div><div className="floating quote"><small>QUOTE APPROVED</small><b>£148.00</b><span>Ready for authorisation</span></div></div></section>
  <section className="logos"><p>MADE FOR THE PEOPLE WHO KEEP HOMES RUNNING</p><div><span>Property managers</span><span>Independent trades</span><span>Build-to-rent teams</span><span>Lettings teams</span></div></section>
  <section className="split intro"><div><p className="kicker">ONE SHARED WORKSPACE</p><h2>From “something’s wrong” to “it’s sorted”.</h2></div><p>Most repair work gets slowed down by missed messages, unclear scope and no reliable proof of completion. Havvo creates one shared timeline so every person knows what happens next.</p></section>
  <section className="steps"><Step number="01" title="Report clearly" text="Tenants share the issue, location and photos in seconds. Smart triage helps the right person see the right context." /><Step number="02" title="Plan with confidence" text="Property teams compare quotes, confirm visits and keep everyone in the same job conversation." /><Step number="03" title="Sign off properly" text="Trades share work evidence. Customers or managers approve the result — in person or remotely — before payment is captured." /></section>
  <section className="audiences"><article className="manager-card"><p className="kicker">FOR PROPERTY TEAMS</p><h2>Less chasing.<br />More control.</h2><p>See every job across your properties, keep approval trails tidy and give residents a much better repair experience.</p><button onClick={() => go("managers")}>Explore for property teams <span>→</span></button></article><article className="trade-card"><p className="kicker">FOR TRADES</p><h2>Good work deserves a smoother way to run.</h2><p>Receive clear jobs, manage the visit from your phone and keep sign-off and payment connected to the work you do.</p><button onClick={() => go("trades")}>Explore for trades <span>→</span></button></article></section>
  <section className="final"><p className="kicker">EARLY ACCESS</p><h2>A better rhythm for property work.</h2><p>Join the Havvo launch list and help shape the first UK release.</p><button className="primary" onClick={() => go("contact")}>Request access <span>→</span></button></section></main> }

function PageView({ page, go, sent, setSent }: { page: Page; go: (page: Page) => void; sent: boolean; setSent: (value: boolean) => void }) {
  if (page === "contact") return <main className="simple"><p className="kicker">EARLY ACCESS</p><h1>Let’s make property work feel simpler.</h1><p className="lede">Tell us a little about your work. We’ll be in touch about the Havvo launch programme.</p>{sent ? <div className="success"><b>You’re on the list.</b><p>Thanks — we’ll be in touch soon.</p></div> : <form onSubmit={(event) => { event.preventDefault(); setSent(true); }}><label>Your name<input required placeholder="Name" /></label><label>Work email<input required type="email" placeholder="you@company.co.uk" /></label><label>I am a<select defaultValue=""><option value="" disabled>Select one</option><option>Property manager</option><option>Trade professional</option><option>Landlord</option><option>Other</option></select></label><label>What would you like Havvo to help with?<textarea rows={4} placeholder="A little context helps us make the launch useful." /></label><button className="primary">Request early access <span>→</span></button></form>}</main>;
  const meta: Record<Exclude<Page,"home"|"contact">, [string,string,string[]]> = { how: ["HOW HAVVO WORKS", "The simple way to keep every repair moving.", ["Report an issue with photos and clear context.", "Bring the right trade into a shared job conversation.", "Approve evidence and capture payment only when work is accepted."]], managers: ["FOR PROPERTY TEAMS", "A calmer control room for every property job.", sections.managers], trades: ["FOR TRADES", "Spend less time chasing. More time doing great work.", sections.trades], pricing: ["PRICING", "Straightforward pricing for a healthier property workflow.", ["Free early-access accounts during the pilot.", "Trade-managed Stripe payments; Havvo never holds your card details.", "Simple platform fees are shown before approval."]], safety: ["SAFETY & TRUST", "Clear records. Human decisions. Safer property work.", ["Urgent hazards always need qualified professional or emergency support.", "AI triage supports the workflow — it never replaces safety judgement.", "Photos, messages, approvals and payments remain attached to the job."]] };
  const [kicker,title,points] = meta[page as Exclude<Page,"home"|"contact">];
  return <main className="simple"><p className="kicker">{kicker}</p><h1>{title}</h1><p className="lede">Havvo gives everyone involved in a repair one reliable place to coordinate the work and see its outcome.</p><div className="point-list">{points.map((point, index) => <div key={point}><span>0{index + 1}</span><p>{point}</p></div>)}</div><button className="primary" onClick={() => go("contact")}>{page === "pricing" ? "Talk about the pilot" : "Request early access"} <span>→</span></button></main>;
}
function Step({ number,title,text }: { number:string;title:string;text:string }) { return <article><span>{number}</span><div className="step-icon">↗</div><h3>{title}</h3><p>{text}</p></article> }
createRoot(document.getElementById("root")!).render(<App />);
